# Continuous Integration (CI) and Code Quality

name: CI
on: [push]
jobs:
  test:
    strategy:
      fail-fast: false 
      matrix:
        python-version: [3.12.0] 
        poetry-version: [1.7.0] 
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }} 

