name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build project
        run: |
          # Add your build commands here
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        uses: actions/configure-pages@v5
        with:
          enablement: true
