#  update actions/checkout action to v4.1.1

name: whitesource-scan

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  WS_SCAN:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2d7d9f7ff5b310f983d059b68785b3c74d8b8edd # v4.1.1

      - name: Download UA
        run: curl -LJO https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar

      - name: Run UA scan
        run: java -jar wss-unified-agent.jar -d $GITHUB_WORKSPACE -noConfig true -apiKey ${{ secrets.WS_ORG_TOKEN }} -product W4D -project "Renovate OS - main" -resolveAllDependencies false -npm_resolveDependencies true || true
